from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls')),  # Includes URLs from the `api` app
BookList.as_view
from rest_framework.routers import DefaultRouter
from .views import BookViewSet

router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # Include routes generated by the router for the BookViewSet
    path('', include(router.urls)),
]

]